### ISSUE TITLE
Great_expectation: incompatible with config version 3.0 due to missing action_list_operator

### ISSUE THREAD

**Issue by mvanuyt** [pandas-profiling/pandas-profiling#769]
**Describe the bug**
When utilizing the great_expectation integration with the newest great_expectation config version, you receive the following error:
DataContextError: No validation operator `action_list_operator` was found in your project. Please verify this in your great_expectations.yml
Originating from
```
[...]pandas_profiling/expectations_report.py", line 100, in to_expectation_suite
    results = data_context.run_validation_operator(
```

**To Reproduce**
Running example 1 from
https://github.com/pandas-profiling/pandas-profiling/blob/develop/examples/features/great_expectations_example.py
using below versions

**Version information:**
Python 3.8.2
great_expectations 0.13.19 (with config_version: 3.0)
pandas_profiling 2.11.0

**Additional context**
Error can be circumvented by adding the following code to great_expectations.yml after init, but this will give a depreciation error when using the new config version of great_expectations:
```
validation_operators:
  action_list_operator:
    class_name: ActionListValidationOperator
    action_list:
    - name: store_validation_result
      action:
        class_name: StoreValidationResultAction
    - name: store_evaluation_params
      action:
        class_name: StoreEvaluationParametersAction
    - name: update_data_docs
      action:
        class_name: UpdateDataDocsAction
```
